###
POST https://{{host}}:{{port}}/test
Content-Type: application/json

{
  "time": 1684769957969,
  "event_type": "event.start",
  "event_data": {
    "type": "race",
    "laps": "50"
  }
}

###
POST https://{{host}}:{{port}}/
Content-Type: application/json

{
  "time": 1684769957969,
  "event_type": "event.change_status",
  "event_data": {
    "old": "running",
    "new": "ended"
  }
}

###
GET https://{{host}}:{{port}}/
Accept: text/plain
